-- ===============================================
-- ASSESSMENT INTEGRATION MIGRATION
-- Date: 2025-11-03
-- Purpose: Token-based assessment claiming system
-- Reference: SUPABASE_SCHEMA_SYNTAX_REFERENCE.md
-- ===============================================

-- ============================================================================
-- 1. CREATE TABLES
-- ============================================================================

-- Table: assessment_tokens
-- Purpose: Stores tokens generated by assessment tool for public results viewing
CREATE TABLE IF NOT EXISTS public.assessment_tokens (
  -- Primary identification
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,

  -- Token identifier (what gets passed in URL)
  token UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),

  -- Assessment data from Airtable
  assessment_data JSONB NOT NULL,

  -- Token lifecycle timestamps (CRITICAL: Use TIMESTAMPTZ not TIMESTAMP)
  created_at TIMESTAMPTZ DEFAULT NOW(),
  expires_at TIMESTAMPTZ DEFAULT (NOW() + INTERVAL '7 days'),
  claimed_at TIMESTAMPTZ,

  -- User who claimed this token
  claimed_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,

  -- Status tracking
  is_used BOOLEAN NOT NULL DEFAULT false,

  -- Audit fields
  source TEXT DEFAULT 'assessment_tool',
  metadata JSONB DEFAULT '{}'::jsonb
);

-- Table: user_assessments
-- Purpose: Stores claimed assessments linked to authenticated users
CREATE TABLE IF NOT EXISTS public.user_assessments (
  -- Primary identification
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,

  -- Foreign keys
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  token_id UUID NOT NULL REFERENCES public.assessment_tokens(id) ON DELETE CASCADE,

  -- Assessment data (denormalized for fast access)
  assessment_data JSONB NOT NULL,

  -- Scores (extracted for easy querying)
  overall_score INTEGER,
  buyer_readiness_score INTEGER,
  technical_readiness_score INTEGER,

  -- Timestamps (CRITICAL: Use TIMESTAMPTZ not TIMESTAMP)
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  last_viewed_at TIMESTAMPTZ,

  -- Constraints
  CONSTRAINT unique_user_assessment UNIQUE(user_id)
);

-- ============================================================================
-- 2. CREATE INDEXES (CRITICAL: Separate CREATE INDEX statements, use IF NOT EXISTS)
-- ============================================================================

-- assessment_tokens indexes
CREATE INDEX IF NOT EXISTS idx_assessment_tokens_token ON public.assessment_tokens(token);
CREATE INDEX IF NOT EXISTS idx_assessment_tokens_claimed_by ON public.assessment_tokens(claimed_by);
CREATE INDEX IF NOT EXISTS idx_assessment_tokens_expires_at ON public.assessment_tokens(expires_at);
CREATE INDEX IF NOT EXISTS idx_assessment_tokens_is_used ON public.assessment_tokens(is_used);
CREATE INDEX IF NOT EXISTS idx_assessment_tokens_created_at ON public.assessment_tokens(created_at DESC);

-- user_assessments indexes
CREATE INDEX IF NOT EXISTS idx_user_assessments_user_id ON public.user_assessments(user_id);
CREATE INDEX IF NOT EXISTS idx_user_assessments_token_id ON public.user_assessments(token_id);
CREATE INDEX IF NOT EXISTS idx_user_assessments_overall_score ON public.user_assessments(overall_score);
CREATE INDEX IF NOT EXISTS idx_user_assessments_created_at ON public.user_assessments(created_at DESC);

-- ============================================================================
-- 3. CREATE TRIGGERS (CRITICAL: DROP first, then CREATE)
-- ============================================================================

-- Trigger for user_assessments updated_at
DROP TRIGGER IF EXISTS update_user_assessments_updated_at ON public.user_assessments;
CREATE TRIGGER update_user_assessments_updated_at
  BEFORE UPDATE ON public.user_assessments
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- ============================================================================
-- 4. ENABLE RLS
-- ============================================================================

ALTER TABLE public.assessment_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_assessments ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- 5. CREATE RLS POLICIES (CRITICAL: DROP first, then CREATE)
-- ============================================================================

-- assessment_tokens policies
DROP POLICY IF EXISTS "Anyone can read tokens by token value" ON public.assessment_tokens;
CREATE POLICY "Anyone can read tokens by token value"
  ON public.assessment_tokens
  FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Service role can insert tokens" ON public.assessment_tokens;
CREATE POLICY "Service role can insert tokens"
  ON public.assessment_tokens
  FOR INSERT
  TO service_role
  WITH CHECK (true);

DROP POLICY IF EXISTS "Service role can update tokens" ON public.assessment_tokens;
CREATE POLICY "Service role can update tokens"
  ON public.assessment_tokens
  FOR UPDATE
  TO service_role
  USING (true);

-- user_assessments policies
DROP POLICY IF EXISTS "Users can read their own assessments" ON public.user_assessments;
CREATE POLICY "Users can read their own assessments"
  ON public.user_assessments
  FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Service role can insert assessments" ON public.user_assessments;
CREATE POLICY "Service role can insert assessments"
  ON public.user_assessments
  FOR INSERT
  TO service_role
  WITH CHECK (true);

DROP POLICY IF EXISTS "Service role can update assessments" ON public.user_assessments;
CREATE POLICY "Service role can update assessments"
  ON public.user_assessments
  FOR UPDATE
  TO service_role
  USING (true);

DROP POLICY IF EXISTS "Users can update their own assessments" ON public.user_assessments;
CREATE POLICY "Users can update their own assessments"
  ON public.user_assessments
  FOR UPDATE
  USING (auth.uid() = user_id);

-- ============================================================================
-- 6. ENABLE REALTIME (CRITICAL: After table creation)
-- ============================================================================

ALTER PUBLICATION supabase_realtime ADD TABLE public.assessment_tokens;
ALTER PUBLICATION supabase_realtime ADD TABLE public.user_assessments;

-- ============================================================================
-- 7. GRANT PERMISSIONS
-- ============================================================================

GRANT ALL ON public.assessment_tokens TO authenticated;
GRANT ALL ON public.user_assessments TO authenticated;

-- ============================================================================
-- 8. ADD COMMENTS
-- ============================================================================

COMMENT ON TABLE public.assessment_tokens IS 'Stores tokens generated by assessment tool for public results viewing';
COMMENT ON TABLE public.user_assessments IS 'Stores claimed assessments linked to authenticated users';

COMMENT ON COLUMN public.assessment_tokens.token IS 'UUID token passed in URL (?token=...)';
COMMENT ON COLUMN public.assessment_tokens.assessment_data IS 'Full assessment data from Airtable including scores, insights, challenges, recommendations';
COMMENT ON COLUMN public.assessment_tokens.is_used IS 'Whether token has been claimed by a user';
COMMENT ON COLUMN public.assessment_tokens.claimed_by IS 'User who claimed this token (null if unclaimed)';
COMMENT ON COLUMN public.assessment_tokens.expires_at IS 'Token expiration date (7 days from creation)';

COMMENT ON COLUMN public.user_assessments.user_id IS 'User who owns this assessment';
COMMENT ON COLUMN public.user_assessments.assessment_data IS 'Denormalized assessment data for fast retrieval';
COMMENT ON COLUMN public.user_assessments.overall_score IS 'Extracted overall score for easy querying/sorting';
COMMENT ON COLUMN public.user_assessments.buyer_readiness_score IS 'Extracted buyer understanding score';
COMMENT ON COLUMN public.user_assessments.technical_readiness_score IS 'Extracted tech-to-value translation score';

-- ============================================================================
-- Sample query examples (for documentation)
-- ============================================================================
-- Validate token:
--   SELECT * FROM assessment_tokens
--   WHERE token = 'xxx' AND is_used = false AND expires_at > NOW();
--
-- Claim token (mark as used):
--   UPDATE assessment_tokens
--   SET is_used = true, claimed_at = NOW(), claimed_by = 'user_id'
--   WHERE token = 'xxx';
--
-- Get user's assessment:
--   SELECT * FROM user_assessments WHERE user_id = 'xxx';
-- ============================================================================
